version: "3.5"

services:
  bitcoind:
    image: bitcoin-core:v25.0
    container_name: bitcoin-core
    volumes:
      - ~/.bitcoin:/root/.bitcoin
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "18443:18443"
      - "18444:18444"
